Merge the chemical model stuffs to the workflow for v15 runs
NOAA-GSL/global-workflow pull request #15
Opened 2020-11-19 19:08 UTC by zhanglikate

Some folders have added into the workflow other than the merging udpates:
1)The gfs_post has been added
2)The prepchem_NC has been added
3)The gsi.fd_chem has been  added

2020-11-19 22:12 UTC, jkhender requested changes

2020-11-19 22:12 UTC, jkhender commented on scripts/exglobal_fcst_nemsfv3gfs.sh
> +    if [ $fsuf = $fsuf = "sfc" ]; then
Should line 342 be if [ $fsuf = "sfc" ]; then

2020-11-19 22:12 UTC, jkhender commented on parm/config/config.base.emc.dyn
> +export CCPP_SUITE="GFS_2017_gfdlmp_gsd_chem"            # GSL:GFS_2017_gfdlmp_gsd_chem
in build_fv3_ccpp_chem.sh, you are compiling only with FV3_GFS_v15_gsd_chem. This needs to be one of the suites you compiled with.  You can list multiple suites when you compile.

Also, the name needs the FV3 at the beginning, "FV3_GFS_2017_gfdlmp_gsd_chem"

2020-11-19 22:12 UTC, jkhender commented on sorc/build_fv3_ccpp_chem.sh
> +./compile.sh "$target" "CCPP=Y 32BIT=Y STATIC=Y SUITES=FV3_GFS_v15_gsd_chem" 2 YES YES  #clean everything and recompile
the suite here should match what is specified in config.base.emc.dyn if you only use 1 to compile with

You can also list multiple suites to compile with

SUITES=FV3_GFS_v15_gsd_chem,FV3_GFS_2017_gfdlmp_gsd_chem"

2020-11-19 22:12 UTC, jkhender commented on sorc/checkout.sh
>      ln -fs fv3gfs_ccpp_chem.fd fv3gfs.fd
still need lines 24, 26, 27, 28 

    cd fv3gfs_ccpp_chem.fd		
     git submodule sync		
     git submodule update --init --recursive		
     cd ${topdir}

do you want to add the hash as in line 25 so everyone always checks out the same version?

2020-11-19 22:12 UTC, jkhender commented on sorc/checkout.sh
> +#echo fv3gfs_ccpp checkout ...
delete lines 29-42

2020-11-19 22:12 UTC, jkhender commented on sorc/checkout.sh
> +    cd prepchem_NC.fd
line 83 is not needed if you are not checking out a specific hash

2020-11-20 00:35 UTC, zhanglikate commented on scripts/exglobal_fcst_nemsfv3gfs.sh
> +    if [ $fsuf = $fsuf = "sfc" ]; then
updated

2020-11-20 00:35 UTC, zhanglikate commented on parm/config/config.base.emc.dyn
> +export CCPP_SUITE="GFS_2017_gfdlmp_gsd_chem"            # GSL:GFS_2017_gfdlmp_gsd_chem
updated

2020-11-20 00:37 UTC, zhanglikate commented on sorc/build_fv3_ccpp_chem.sh
> +./compile.sh "$target" "CCPP=Y 32BIT=Y STATIC=Y SUITES=FV3_GFS_v15_gsd_chem" 2 YES YES  #clean everything and recompile
Already updated  the config.based

2020-11-20 00:50 UTC, zhanglikate reviewed
Updated based on  the review

2020-11-20 00:50 UTC, zhanglikate commented on sorc/checkout.sh
> +#echo fv3gfs_ccpp checkout ...
Updated

2020-11-20 00:50 UTC, zhanglikate commented on sorc/checkout.sh
> +    cd prepchem_NC.fd
Which line did you mean?

2020-11-20 00:51 UTC, zhanglikate commented on sorc/checkout.sh
>      ln -fs fv3gfs_ccpp_chem.fd fv3gfs.fd
updated

2020-11-20 01:06 UTC, jkhender commented on sorc/checkout.sh
> +    cd prepchem_NC.fd
line 83 is 
    cd prepchem_NC.fd     (now line 73 in updated file)

2020-11-20 01:15 UTC, jkhender requested changes
In checkout.sh,  remove this line

    cd prepchem_NC.fd

2020-11-20 01:18 UTC, jkhender approved these changes

2020-11-20 01:19 UTC, merged